name: Keep Streamlit App Alive

on:
  schedule:
    # Runs every 12 hours
    - cron: '0 */12 * * *'
  
  # Optional: Allow manual triggering to test the workflow
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run ping script
      run: python ping_bot.py
      
    # Removing the problematic upload-artifact step since it's causing issues
    # We can add it back later with a different version if needed
